# Fishing Frenzy Plugin Configuration
# All values can be hot-reloaded with /frenzy reload

# Enable verbose logging for troubleshooting
debug: false

frenzy:
  duration: 90 # seconds (default for shared meter)
  cooldown: 3600 # seconds (global cooldown)
  per-player-cooldown: 600 # seconds (per-player cooldown)
  loot-multiplier: 1.0 # multiplier for loot drop chances
  # Empty list allows all worlds (recommended default). Add names to restrict.
  allowed-worlds: []
  allowed-biomes: [] # empty = allow all, or e.g. ["PLAINS", "RIVER", "OCEAN"]
  allowed-times:
    - DAY
    - NIGHT
  mode: global # 'global' or 'per-player'
  meter:
    enabled: true
    required-fish: 100 # number of fish to fill meter
    bossbar-title: '<gradient:aqua:blue>Frenzy Meter: <white><progress>'
    color: BLUE
    style: SEGMENTED_20
  streaks:
    enabled: true
    luck-per-streak: 0.05 # 5% extra chance per streak
    max-streak: 5
  pity-threshold: 15 # Number of catches before guaranteed spicy loot
  loot-table:
    # Spicy (rare) loot
    - type: ELYTRA
      weight: 1
      spicy: true
      amount: 1
    - type: NETHERITE_SCRAP
      weight: 2
      spicy: true
      amount: 1-2
    - type: TRIDENT
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - LOYALTY:3
        - IMPALING:5
        - UNBREAKING:3
    - type: ENCHANTED_GOLDEN_APPLE
      weight: 1
      spicy: true
      amount: 1
    - type: TOTEM_OF_UNDYING
      weight: 2
      spicy: true
      amount: 1
    - type: HEART_OF_THE_SEA
      weight: 2
      spicy: true
      amount: 1
    - type: DIAMOND_HELMET
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION:4
        - UNBREAKING:3
        - RESPIRATION:3
    - type: DIAMOND_CHESTPLATE
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION:4
        - UNBREAKING:3
    - type: DIAMOND_LEGGINGS
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION:4
        - UNBREAKING:3
    - type: DIAMOND_BOOTS
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION:4
        - UNBREAKING:3
        - DEPTH_STRIDER:3
    - type: NETHERITE_HELMET
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION:4
        - UNBREAKING:3
        - RESPIRATION:3
    - type: NETHERITE_CHESTPLATE
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION:4
        - UNBREAKING:3
    - type: NETHERITE_LEGGINGS
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION:4
        - UNBREAKING:3
    - type: NETHERITE_BOOTS
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION:4
        - UNBREAKING:3
        - DEPTH_STRIDER:3
    - type: FISHING_ROD
      weight: 1
      spicy: true
      amount: 1
      name: "<gradient:gold:yellow>Lucky Rod</gradient>"
      lore:
        - "<gray>A legendary rod said to bring fortune."
        - "<yellow>Boosts your chance for spicy loot!"
      enchants:
        - LUCK_OF_THE_SEA:3
        - LURE:3
        - UNBREAKING:3
        - MENDING:1
      lucky-rod: true
    # Uncommon loot
    - type: ENCHANTED_BOOK
      weight: 10
      enchants:
        - LURE:3
        - LUCK_OF_THE_SEA:3
        - MENDING:1
        - UNBREAKING:3
        - PROTECTION:4
        - DEPTH_STRIDER:3
        - FROST_WALKER:2
        - RESPIRATION:3
        - SILK_TOUCH:1
        - EFFICIENCY:5
        - SHARPNESS:5
    - type: DIAMOND
      weight: 8
      amount: 2-4
    - type: NAUTILUS_SHELL
      weight: 6
      amount: 1-2
    - type: NAME_TAG
      weight: 5
      amount: 1
    # Example of a multi-effect potion (you can duplicate and tweak)
    - type: POTION
      weight: 6
      amount: 1-2
      name: "<aqua>Oceanic Draught"
      potion:
        # Optional base potion data (type + extended/upgraded like vanilla)
        base:
          type: WATER_BREATHING
          extended: true
          upgraded: false
        # Optional custom color (supports "#RRGGBB", "R,G,B", [R,G,B], or named like RED)
        color: "#00AEEF"
        # Custom effects stack on top of base; duration is in seconds unless 'ticks: true'
        effects:
          - type: DOLPHINS_GRACE
            duration: 45
            level: 1
            ambient: false
            particles: true
            icon: true
          - type: NIGHT_VISION
            duration: 120
            level: 1
    # You can also do splash/lingering or tipped arrows with potion data, e.g.:
    # - type: SPLASH_POTION
    #   weight: 3
    #   potion:
    #     base: { type: HEALING, upgraded: true }
    # - type: TIPPED_ARROW
    #   weight: 2
    #   potion:
    #     effects:
    #       - { type: POISON, duration: 5, level: 2 }
    # Common loot
    - type: COOKED_COD
      weight: 20
      amount: 4-8
    - type: COD
      weight: 20
      amount: 4-8
    - type: SALMON
      weight: 15
      amount: 2-6
    - type: PUFFERFISH
      weight: 10
      amount: 1-2
    - type: BONE
      weight: 10
      amount: 2-6
    - type: LEATHER
      weight: 8
      amount: 1-3
    # ... add more loot as desired
