# Fishing Frenzy Plugin Configuration
# All values can be hot-reloaded with /frenzy reload

frenzy:
  duration: 90 # seconds (default for shared meter)
  cooldown: 3600 # seconds (global cooldown)
  per-player-cooldown: 600 # seconds (per-player cooldown)
  loot-multiplier: 1.0 # multiplier for loot drop chances
  allowed-worlds:
    - world
  allowed-biomes: [] # empty = allow all, or e.g. ["PLAINS", "RIVER", "OCEAN"]
  allowed-times:
    - DAY
    - NIGHT
  mode: global # 'global' or 'per-player'
  meter:
    enabled: true
    required-fish: 100 # number of fish to fill meter
    bossbar-title: '<gradient:aqua:blue>Frenzy Meter: <white><progress>'
    color: BLUE
    style: SEGMENTED_20
  streaks:
    enabled: true
    luck-per-streak: 0.05 # 5% extra chance per streak
    max-streak: 5
  pity-threshold: 15 # Number of catches before guaranteed spicy loot
  loot-table:
    # Spicy (rare) loot
    - type: ELYTRA
      weight: 1
      spicy: true
      amount: 1
    - type: NETHERITE_SCRAP
      weight: 2
      spicy: true
      amount: 1-2
    - type: TRIDENT
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - LOYALTY
        - IMPALING
        - UNBREAKING
    - type: ENCHANTED_GOLDEN_APPLE
      weight: 1
      spicy: true
      amount: 1
    - type: TOTEM_OF_UNDYING
      weight: 2
      spicy: true
      amount: 1
    - type: HEART_OF_THE_SEA
      weight: 2
      spicy: true
      amount: 1
    - type: DIAMOND_HELMET
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION
        - UNBREAKING
        - RESPIRATION
    - type: DIAMOND_CHESTPLATE
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION
        - UNBREAKING
    - type: DIAMOND_LEGGINGS
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION
        - UNBREAKING
    - type: DIAMOND_BOOTS
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION
        - UNBREAKING
        - DEPTH_STRIDER
    - type: NETHERITE_HELMET
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION
        - UNBREAKING
        - RESPIRATION
    - type: NETHERITE_CHESTPLATE
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION
        - UNBREAKING
    - type: NETHERITE_LEGGINGS
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION
        - UNBREAKING
    - type: NETHERITE_BOOTS
      weight: 1
      spicy: true
      amount: 1
      enchants:
        - PROTECTION
        - UNBREAKING
        - DEPTH_STRIDER
    - type: FISHING_ROD
      weight: 1
      spicy: true
      amount: 1
      name: "<gradient:gold:yellow>Lucky Rod</gradient>"
      lore:
        - "<gray>A legendary rod said to bring fortune."
        - "<yellow>Boosts your chance for spicy loot!"
      enchants:
        - LUCK_OF_THE_SEA
        - LURE
        - UNBREAKING
        - MENDING
      lucky-rod: true
    # Uncommon loot
    - type: ENCHANTED_BOOK
      weight: 10
      enchants:
        - LURE
        - LUCK_OF_THE_SEA
        - MENDING
        - UNBREAKING
        - PROTECTION
        - DEPTH_STRIDER
        - FROST_WALKER
        - RESPIRATION
        - SILK_TOUCH
        - EFFICIENCY
        - SHARPNESS
    - type: DIAMOND
      weight: 8
      amount: 2-4
    - type: NAUTILUS_SHELL
      weight: 6
      amount: 1-2
    - type: NAME_TAG
      weight: 5
      amount: 1
    # Common loot
    - type: COOKED_COD
      weight: 20
      amount: 4-8
    - type: COD
      weight: 20
      amount: 4-8
    - type: SALMON
      weight: 15
      amount: 2-6
    - type: PUFFERFISH
      weight: 10
      amount: 1-2
    - type: BONE
      weight: 10
      amount: 2-6
    - type: LEATHER
      weight: 8
      amount: 1-3
    # ... add more loot as desired
